version: '2'
services:
  api:
    build:
      context: ./API/
    hostname: api
    command: npm start
    ports:
      - "8080:8080"
    environment:
      - MONGOURI=mongodb://tomas:t123456@ds119662.mlab.com:19662/technology-fighter-z
      # - SECRETORKEY=${SECRETORKEY}
      - PORT=8080
      - NODE_ENV=development
      
  client:
    build:
      context: ./Client/
    hostname: client
    command: npm start
    depends_on:
      - api
    ports:
      - "3000:3000"
    links:
      - api
      
  nginx:
    image: valian/docker-nginx-auto-ssl
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - '80'
      - '443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/ssl-data:/etc/resty-auto-ssl
    depends_on:
      - api
      - client
    links:
      - api
      - client